export const datas = [
  {
    ner: "Swiss Apls",
    imageURL: "/pic/12.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Beaches",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/33.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Deserts",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/30.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Mountains",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/29.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Tropical",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/34.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Skiing",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/28.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Castles",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/24.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Camping",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/26.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Countryside",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/27.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Houseboats",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/22.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Iconic Cities",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/12.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Beaches",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/33.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Deserts",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/30.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Mountains",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/29.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Tropical",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/34.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Skiing",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/28.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Castles",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/24.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Camping",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/26.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Countryside",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/27.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Houseboats",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/22.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Iconic Cities",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/12.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Beaches",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/33.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Deserts",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/30.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Mountains",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/29.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Tropical",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/34.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Skiing",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/28.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Castles",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/24.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Camping",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/26.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Countryside",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/27.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Houseboats",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/22.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Iconic Cities",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/12.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Beaches",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/33.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Deserts",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/30.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Mountains",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/29.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Tropical",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/34.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Skiing",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/28.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Castles",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/24.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Camping",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/26.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Countryside",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/27.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Houseboats",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/22.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Iconic Cities",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/12.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Beaches",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/33.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Deserts",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/30.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Mountains",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/29.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Tropical",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/34.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Skiing",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/28.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Castles",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/24.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Camping",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/26.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Countryside",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/27.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Houseboats",
  },
  {
    ner: "Swiss Apls",
    imageURL: "/pic/22.png",
    time: "3Days 4 Nights",
    rating: "4.7",
    typeimageURL: "/pic/40.png",
    typeone: "Tour combo with return airport transfer",
    typetwo: "City Tour",
    typethree: "Curious Corner",
    typefour: "₹88,952",
    typefive: "₹88,952",
    typesix: "Per person",
    minimapname: "2 Flights",
    minimapURL: "/pic/41.svg",
    minimapnametwo: "1 Hotel",
    minimaptwoURL: "/pic/42.svg",
    minimapnamethree: "2 Transfers",
    minimapthreeURL: "/pic/43.svg",
    minimapnamefour: "4 Activities",
    minimaptourURL: "/pic/44.svg",
    category: "Iconic Cities",
  },
];
export default datas;
