export const datas = [
  {
    imgUTL: "../img/category/beach/Beachhouse.png",
    title: "Beach House",
    bairsgil: "Vietnam",
    tovch: "Vieetnamese",
    id: "1",
    category: "Beaches",
    rating: "3.6",
    price: "$88.92",
  },
  {
    imgUTL: "../img/category/beach/beach2.png",
    title: "Beach Bar",
    bairsgil: "Sanya China",
    tovch: "Bakeries",
    id: "2",
    category: "Beaches",
    rating: "4",
    price: "$90",
    day: "3day 2night",
  },
  {
    imgUTL: "../img/category/beach/beach3.png",
    title: "Beachhouse at the Moana",
    bairsgil: "United States",
    tovch: "American",
    id: "3",
    category: "Beaches",
    rating: "4.2",
    price: "$88",
    day: "2day 1night",
  },
  {
    imgUTL: "../img/category/beach/beach4.png",
    title: "Beach Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "american",
    id: "4",
    category: "Beaches",
    rating: "3.7",
    price: "$93",
    day: "3day 2 night",
  },
  {
    imgUTL: "../img/category/desert/2.png",
    title: "Desert Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Mediterranean",
    id: "6",
    category: "Deserts",
    rating: "3.5",
    price: "$80",
    day: "3day 2 night",
  },
  {
    imgUTL: "../img/category/desert/1.png",
    title: "Desert Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "5",
    category: "Deserts",
    rating: "3",
    price: "$70",
    day: "2 day 1 night",
  },
  {
    imgUTL: "../img/category/desert/3.png",
    title: "Desert Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "american",
    id: "7",
    category: "Deserts",
    rating: "4",
    price: "$100",
    day: "3day 2 night",
  },
  {
    imgUTL: "../img/category/desert/4.png",
    title: "Desert Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "8",
    category: "Deserts",
    rating: "3.8",
    price: "$97",
    day: "4 day 3 night",
  },
  {
    imgUTL: "../img/category/mountain/aconcagua.png",
    title: "Mountain Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "9",
    category: "Mountains",
    rating: "4.6",
    price: "$94",
    day: "3day 2night",
  },
  {
    imgUTL: "../img/category/mountain/chimborazo.png",
    title: "Mountain Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "10",
    category: "Mountains",
    rating: "4.7",
    price: "$92",
    day: "4day 3 night",
  },
  {
    imgUTL: "../img/category/mountain/denali.png",
    title: "Mountain Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "11",
    category: "Mountains",
    rating: "3.5",
    price: "$100",
    day: "2 day 1 night",
  },
  {
    imgUTL: "../img/category/mountain/guardian.png",
    title: "Mountain Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "12",
    category: "Mountains",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/iconic/dubai.png",
    title: "Dubai",
    bairsgil: "Dubai",
    tovch: "Bars",
    id: "13",
    category: "Iconic Cities",
    rating: "3.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/iconic/korea.png",
    title: "South Korea",
    bairsgil: "South Korea",
    tovch: "Bars",
    id: "14",
    category: "Iconic Cities",
    rating: "4.6",
    price: "$90",
    day: "1day",
  },
  {
    imgUTL: "../img/category/iconic/london.png",
    title: "London",
    bairsgil: "London",
    tovch: "Bars",
    id: "15",
    category: "Iconic Cities",
    rating: "3",
    price: "$80",
    day: "2day 1 night",
  },
  {
    imgUTL: "../img/category/iconic/spain.png",
    title: "Spain",
    bairsgil: "Spain",
    tovch: "Bars",
    id: "16",
    category: "Iconic Cities",
    rating: "3.4",
    price: "$100",
    day: "2day 1night",
  },
  {
    imgUTL: "../img/category/House/1.png",
    title: "Dubai",
    bairsgil: "Dubai",
    tovch: "Bars",
    id: "17",
    category: "Houseboats",
    rating: "3.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/House/2.png",
    title: "South Korea",
    bairsgil: "South Korea",
    tovch: "Bars",
    id: "18",
    category: "Houseboats",
    rating: "4.6",
    price: "$90",
    day: "1day",
  },
  {
    imgUTL: "../img/category/House/3.png",
    title: "London",
    bairsgil: "London",
    tovch: "Bars",
    id: "19",
    category: "Houseboats",
    rating: "3",
    price: "$80",
    day: "2day 1 night",
  },
  {
    imgUTL: "../img/category/House/4.png",
    title: "Spain",
    bairsgil: "Spain",
    tovch: "Bars",
    id: "20",
    category: "Houseboats",
    rating: "3.4",
    price: "$100",
    day: "2day 1night",
  },
  {
    imgUTL: "../img/category/country/1.png",
    title: "Country Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bistros",
    id: "21",
    category: "Country side",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/country/2.jpg",
    title: "Country Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "American",
    id: "22",
    category: "Country side",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/country/3.jpg",
    title: "Country Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Shopping",
    id: "23",
    category: "Country side",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/country/4.jpg",
    title: "Country Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "",
    id: "24",
    category: "Country side",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/camping/1.jpg",
    title: "Camping Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "25",
    category: "Camping",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/camping/2.jpg",
    title: "Camping Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "26",
    category: "Camping",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/camping/3.jpg",
    title: "Camping Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "27",
    category: "Camping",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/camping/4.jpg",
    title: "Camping Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "28",
    category: "Camping",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/castles/1.jpg",
    title: "Castles Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "29",
    category: "Castles",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/castles/2.jpg",
    title: "Castles Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "30",
    category: "Castles",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/castles/3.jpg",
    title: "Castles Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "31",
    category: "Castles",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/castles/4.jpg",
    title: "Castles Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "32",
    category: "Castles",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/ski/1.jpg",
    title: "Ski Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "33",
    category: "Skiing",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/ski/2.jpg",
    title: "Ski Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "34",
    category: "Skiing",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/ski/3.jpg",
    title: "Ski Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "35",
    category: "Skiing",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/ski/4.jpg",
    title: "Ski Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "36",
    category: "Skiing",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/tropical/2.jpg",
    title: "Tropical Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "37",
    category: "Tropical",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/tropical/1.jpg",
    title: "Tropical Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "38",
    category: "Tropical",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/tropical/4.jpg",
    title: "Tropical Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "39",
    category: "Tropical",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
  {
    imgUTL: "../img/category/tropical/3.jpg",
    title: "Tropical Club",
    bairsgil: "Kuala Mayaysia",
    tovch: "Bars",
    id: "40",
    category: "Tropical",
    rating: "2.6",
    price: "$70",
    day: "1day",
  },
];
export default datas;
